### PR TITLE
Use ifalias for Planned Maintenance "str" and "regexp" matching

### LINKED ISSUE #297: Possible wrong value used for port matching in planned maintenance
Looking through the OG zino1 code, it uses `$portToLocIfDescr` for matching against ports. I think that might contain `ifalias` values, while `$portToIfDescr` contains `ifdescr`. The PM code right now uses `port.ifdescr` for matching, but maybe it should be changed to `port.ifalias`?

### PR DESCRIPTION
**Pull request by stveit**
## Scope and purpose

Fixes #297

Original zino seems to use ifalias and ifdescr for planned maintenance matching, while intitial PM implementation used only ifdescr.
This PR changes it to use ifalias where applicable instead. 

Original zino code confuses me so wouldn't be a bad idea for someone else to take a look and see if this PR actually makes the correct changes

## Contributor Checklist

Every pull request should have this checklist filled out, no matter how small it is.
More information about contributing to Zino can be found in the
[README](https://github.com/Uninett/zino/blob/master/README.md#developing-zino).

* [x] Added a changelog fragment for [towncrier](https://github.com/Uninett/zino/blob/master/README.md#before-merging-a-pull-request)
* [X] Added/amended tests for new/changed code 
* [ ] Added/changed documentation
* [X] Linted/formatted the code with black, ruff and isort, easiest by using [pre-commit](https://github.com/Uninett/zino/blob/master/README.md#code-style)
* [X] The first line of the commit message continues the sentence "If applied, this commit will ...", starts with a capital letter, does not end with punctuation and is 50 characters or less long. See https://cbea.ms/git-commit/
* [ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done

### CODE REVIEW

**Comment by johannaengland** [comment]
I would like to have a news fragment for that, because this is a functionality change

**Review by johannaengland — APPROVED** [review]

**Comment by stveit** [comment]
Did another look on original code, and seems it uses both ifalias and ifdescr in different situations. I have changed things to reflect that

File: changelog.d/297.fixed.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix PM matching wrongly using ifdescr instead of the correct ifalias
```
Comment (johannaengland) [inline changelog.d/297.fixed.md:1]: Please update this to be more concrete on when `ifalias` is used for matching

**Review by johannaengland — APPROVED** [review]

**Review by lunkwill42 — APPROVED** [review]

File: changelog.d/297.fixed.md (hunk 1 above)
Comment (lunkwill42) [reply changelog.d/297.fixed.md]: I can grok both versions, so resolving this. As release manager, I reserve the right to rewrite any and all changelog entries as I see fit before committing the compiled changelog :)
